baseURL: "https://digicre.net/welcome/"
cleanDestinationDir: true
disableHugoGeneratorInject: true
hasCJKLanguage: true
title: "デジクリの紹介 - 芝浦工業大学 デジクリ"

disableKinds:
  - "RSS"
  - "taxonomy"
  - "term"

params:
  description: "創作活動をしたい方は必見！　芝浦工業大学のサークル「デジクリ」をご紹介します。"

menu:
  join-us:
    - name: "入部受付"
      url: "https://forms.gle/cY25Kc6fssqv2tZz9"
  links:
    - identifier: "twitter"
      name: "X (Twitter)"
      url: "https://twitter.com/sitdigicre"
      weight: 10
    - identifier: "youtube"
      name: "YouTube"
      url: "https://www.youtube.com/@sitdigicre"
      weight: 20
    - identifier: "line"
      name: "LINE オープンチャット"
      url: "https://line.me/ti/g2/HParErij--I835lSEnSJeevqTnb_YTRqx-Movw"
      weight: 30
    - identifier: "digicre"
      name: "ウェブサイト"
      url: "https://digicre.net"
      weight: 40
    - identifier: "contact"
      name: "お問い合わせ"
      url: "mailto:contact@digicre.net"
      weight: 50
  pv:
    - identifier: "nnJ5ml6D2UE" # YouTube の動画 ID
      name: "デジクリ紹介動画"
  event:
    - identifier: "YzgxYWVkNzczZjQ0ZWMxNWNhOWI1ODRlZWVjN2I0ODZmY2JkZmEzNzMyZTc4ZTE2YTQ0MDZiMzFiYTAwMDNlOUBncm91cC5jYWxlbmRhci5nb29nbGUuY29t" # Google Calendar の ID
      name: "新歓イベント日程"
  teams:
    - identifier: "pg"
      name: "PG 班"
      url: "https://digicre.net/about/pg"
      weight: 10
    - identifier: "sys-dev"
      name: "SysDev 班"
      url: "https://digicre.net/about/sysdev"
      weight: 20
    - identifier: "2dcg"
      name: "イラスト班"
      url: "https://digicre.net/about/2dcg"
      weight: 30
    - identifier: "3dcg"
      name: "3DCG 班"
      url: "https://digicre.net/about/3dcg"
      weight: 40
    - identifier: "dtm"
      name: "DTM 班"
      url: "https://digicre.net/about/dtm"
      weight: 50
    - identifier: "movie"
      name: "Movie 班"
      url: "https://digicre.net/about/movie"
      weight: 60
    - identifier: "v-tuber"
      name: "VTuber 班"
      url: "https://www.youtube.com/channel/UCgh1tbd7SC4qv9A6RffbB0g"
      weight: 70
    - identifier: "xr"
      name: "xR 班"
      url: "https://digicre.net/about/xr"
      weight: 80
    - identifier: "writing"
      name: "文字書き班"
      url: ""
      weight: 90
