baseURL: "https://digicre.net/welcome/"
title: "デジクリ"
disableHugoGeneratorInject: true
hasCJKLanguage: true

disableKinds:
  - "taxonomy"
  - "term"
  - "RSS"

params:
  description: ""
  images:
    - "img/ogp.png"

menu:
  join-us:
    - name: "参加申込"
      url: "https://forms.gle/KQMZuZ9YYL832Vc66" # 実際のフォーム URL に書き換えること
  links:
    - identifier: "twitter"
      name: "Twitter"
      url: "https://twitter.com/sitdigicre"
      weight: 10
    - identifier: "youtube"
      name: "YouTube"
      url: "https://www.youtube.com/@sitdigicre"
      weight: 20
    - identifier: "digicre"
      name: "ウェブサイト"
      url: "https://digicre.net"
      weight: 30
    - identifier: "contact"
      name: "お問い合わせ"
      url: "mailto:contact@digicre.net"
      weight: 40
  pv:
    - identifier: "pv"
      name: "デジクリ紹介動画"
      url: "https://www.youtube.com/embed/EaFvRsJAV9U?autoplay=1&mute=1&modestbranding=1&playsinline=1&disablekb=1&loop=1&controls=0&playlist=EaFvRsJAV9U"
  teams:
    - identifier: "pg"
      name: "PG 班"
      url: "https://digicre.net/about/pg"
      weight: 10
    - identifier: "2dcg"
      name: "イラスト班"
      url: "https://digicre.net/about/2dcg"
      weight: 20
    - identifier: "3dcg"
      name: "3DCG 班"
      url: "https://digicre.net/about/3dcg"
      weight: 30
    - identifier: "dtm"
      name: "DTM 班"
      url: "https://digicre.net/about/dtm"
      weight: 40
    - identifier: "movie"
      name: "Movie 班"
      url: "https://digicre.net/about/movie"
      weight: 50
    - identifier: "v-tuber"
      name: "VTuber 班"
      url: "https://www.youtube.com/channel/UCgh1tbd7SC4qv9A6RffbB0g"
      weight: 60
    - identifier: "xr"
      name: "xR 班"
      url: ""
      weight: 70
    - identifier: "sys-dev"
      name: "SysDev 班"
      url: ""
      weight: 80
  schedule:
    - identifier: "events"
      name: "新歓スケジュール"
      url: "https://calendar.google.com/calendar/embed?height=320&wkst=1&bgcolor=%23ffffff&ctz=Asia%2FTokyo&title&showTitle=0&showNav=1&showPrint=0&showCalendars=0&showTz=0&hl=ja&src=c2l0ZGlnaWNyZWNpcmNsZUBnbWFpbC5jb20&color=%23138fcc"
