name: "Publish on GitHub Pages"

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: "ubuntu-22.04"
    concurrency:
      group: "${{ github.workflow }}-${{ github.ref }}"
    steps:
      - uses: "actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3" # v3.5.0

      - name: "Set up Hugo"
        uses: "peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d" # renovate: tag=v2.6.0
        with:
          hugo-version: "0.111.3"
          extended: true

      - name: "Set up Node.js"
        uses: "actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7" # v3.8.2
        with:
          node-version: 18

      - name: "Install npm dependencies"
        run: "npm ci"

      - name: "Format codes"
        run: "npm run format"

      - name: "Build"
        run: "npm run build"

      - name: "Deploy"
        uses: "peaceiris/actions-gh-pages@bd8c6b06eba6b3d25d72b7a1767993c0aeee42e7" # renovate: tag=v3.9.2
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          publish_dir: "./public"
          cname: "digicre.net"
