name: "Publish on GitHub Pages"

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: "ubuntu-22.04"
    concurrency:
      group: "${{ github.workflow }}-${{ github.ref }}"
    steps:
      - uses: "actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c"

      - name: "Set up Hugo"
        uses: "peaceiris/actions-hugo@7c4b9f1f99c72728600c292c1f0e7138cc3a8865"
        with:
          hugo-version: "0.111.3"
          extended: true

      - name: "Set up Node.js"
        uses: "actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c"
        with:
          node-version: 18

      - name: "Install npm dependencies"
        run: "npm ci"

      - name: "Format codes"
        run: "npm run format"

      - name: "Build"
        run: "npm run build"

      - name: "Deploy"
        uses: "peaceiris/actions-gh-pages@bd8c6b06eba6b3d25d72b7a1767993c0aeee42e7"
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          publish_dir: "./public"
          cname: "digicre.net"
